### ISSUE TITLE
Help！

### ISSUE THREAD

**Issue by MachineLearning0123** [qbdl/SingleStream-SLT#1]
Hi, I have deployed the pre-trained model and the trained model locally, do you know how to fix this error report?🙂

Traceback (most recent call last):
  File "prediction.py", line 227, in <module>
    do_translation=do_translation, do_recognition=do_recognition)
  File "prediction.py", line 60, in evaluation
    for step, batch in enumerate(val_dataloader):
  File "E:\Anaconda\envs\sslt\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "E:\Anaconda\envs\sslt\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "E:\Anaconda\envs\sslt\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "E:\Anaconda\envs\sslt\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "E:\Anaconda\envs\sslt\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Anaconda\envs\sslt\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\Anaconda\envs\sslt\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\Anaconda\envs\sslt\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

**Comment by qbdl** [comment]
It's probably because the wrong with DataLoader, you may change numer_workers to 0 to solve this problem.
"DataLoader(your_dataset, num_workers=0, ...)"

**Comment by MachineLearning0123** [comment]
> It's probably because the wrong with DataLoader, you may change numer_workers to 0 to solve this problem. "DataLoader(your_dataset, num_workers=0, ...)"

Hello, thank you for your patience, I followed your method to change the num_workers of dataloader from 4 to 0, and change the batch_size repair from 8 to 1, the test code won't report error, but there is no running result, please ask the 8G video memory of the video card is enough to run the test code?🙂

**Comment by qbdl** [comment]
Have you write some code to output some intermediate process results?(for check if it's running) 
But I don't know if 8G video memory is enough.

**Comment by qbdl** [comment]
Have you written some code to output some intermediate process results?(for check if it's running)
But I don't know if 8G video memory is enough.

**Comment by MachineLearning0123** [comment]
> Have you written some code to output some intermediate process results?(for check if it's running) But I don't know if 8G video memory is enough.

I did it along the lines of what you reproduced without changing the code much. Maybe it's just my gpu math that's lacking. Anyway thanks for your reply! Best wishes!
